from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('indexTallermlween', views.indexTallermlween, name='indexTallermlween'),
    path('inicio_sesion_usuario', views.inicio_sesion_usuario, name='inicio_sesion_usuario'),
    path('inicio_sesion_mec_admi', views.inicio_sesion_mec_admi, name='inicio_sesion_mec_admi'),
    path('menu', views.menu, name='menu'),
    path('iniciar_session_como_mecanico', views.iniciar_session_como_mecanico, name='iniciar_session_como_mecanico'),
    path('registro_de_usuario', views.registro_de_usuario, name='registro_de_usuario'),
    path('IniciarSesion_adr', views.IniciarSesion_adr, name='IniciarSesion_adr'),
    path('cuenta_angel_d_revilla', views.cuenta_angel_d_revilla, name='cuenta_angel_d_revilla'),
    path('formulario_atenciones_CORREGIDO', views.formulario_atenciones_CORREGIDO, name='formulario_atenciones_CORREGIDO'),
    path('listado_atenciones', views.listado_atenciones, name='listado_atenciones'),
    path('listado_atenciones_usuario', views.listado_atenciones_usuario, name='listado_atenciones_usuario'),
    path('listado_atenciones_usuario2', views.listado_atenciones_usuario2, name='listado_atenciones_usuario2'),
    path('agregar_atenciones', views.agregar_atenciones, name='agregar_atenciones'),
    path('modificar_atenciones/<str:pk>', views.modificar_atenciones, name='modificar_atenciones'),
    path('eliminar_atenciones/<str:pk>', views.eliminar_atenciones, name='eliminar_atenciones'),
    path('update_atenciones', views.update_atenciones, name='update_atenciones'),
    path('Ver_atenciones_por', views.Ver_atenciones_por, name='Ver_atenciones_por'),
    path('Ver_atenciones_x_mecanico', views.Ver_atenciones_x_mecanico, name='Ver_atenciones_x_mecanico'),
    path('detalle_trabajo1_mecanica_makween_23/<str:id>/', views.detalle_trabajo1_mecanica_makween_23, name='detalle_trabajo1_mecanica_makween_23'),
    path('detalle_trabajo2_makween_23', views.detalle_trabajo2_makween_23, name='detalle_trabajo2_makween_23'),
    path('detalle_trabajo3_makween_23', views.detalle_trabajo3_makween_23, name='detalle_trabajo3_makween_23'),
    path('atencion_añadida_success_gp', views.atencion_añadida_success_gp, name='atencion_añadida_success_gp'),
    path('Estado_antenciones_adr', views.Estado_antenciones_adr, name='Estado_antenciones_adr'),
    path('Estado_antenciones_gp', views.Estado_antenciones_gp, name='Estado_antenciones_gp'),
    path('Estado_antenciones_jg', views.Estado_antenciones_jg, name='Estado_antenciones_jg'),
    path('formulario_enviado_succes', views.formulario_enviado_succes, name='formulario_enviado_succes'),
    path('Formulario_contacto', views.Formulario_contacto, name='Formulario_contacto'),
    path('mantenciones_ingresadas_usuario', views.mantenciones_ingresadas_usuario, name='mantenciones_ingresadas_usuario'),
    path('nueva_atencion_añadida_success_adr', views.nueva_atencion_añadida_success_adr, name='nueva_atencion_añadida_success_adr'),
    path('registro_existoso', views.registro_existoso, name='registro_existoso'),
    path('ate_aprobada', views.ate_aprobada, name='ate_aprobada'),
    path('ate_rechazada', views.ate_rechazada, name='ate_rechazada'),
    path('modificar_atenciones_us/<str:pk>', views.modificar_atenciones_us, name='modificar_atenciones_us'),
    path('update_atenciones_us', views.update_atenciones_us, name='update_atenciones_us'),
    path('modificar_atenciones_ususario/<str:pk>', views.modificar_atenciones_usuario, name='modificar_atenciones_usuario'),
    path('update_atenciones_ususario', views.update_atenciones_usuario, name='update_atenciones_usuario'),
    path('eliminar_atenciones_usuario/<str:pk>', views.eliminar_atenciones_usuario, name='eliminar_atenciones_usuario'),
    path('buscar_atencion/', views.buscar_atencion, name='buscar_atencion'),
    path('detalle_trabajo_ultima_fecha', views.detalle_trabajo_ultima_fecha, name='detalle_trabajo_ultima_fecha'),
    path('detalle_trabajo_ultima_fecha2/', views.detalle_trabajo_ultima_fecha2, name='detalle_trabajo_ultima_fecha2'),
    path('detalle_trabajo_ultima_fecha3/', views.detalle_trabajo_ultima_fecha3, name='detalle_trabajo_ultima_fecha3'),
    path('ingresar_atenciones_carro', views.ingresar_atenciones_carro, name='ingresar_atenciones_carro'),
]