# Generated by Django 4.0.5 on 2023-06-27 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formularioContacto',
            fields=[
                ('nombreCliente', models.CharField(db_column='nombreCliente', max_length=255, primary_key=True, serialize=False)),
                ('correoGmail', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('marca', models.CharField(max_length=30)),
                ('modeloAuto', models.CharField(max_length=50)),
                ('tipoServicio', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('trabajo', models.CharField(db_column='trabajo', max_length=255, primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=50)),
                ('fecha', models.DateField(max_length=50)),
                ('modeloAuto', models.CharField(max_length=50)),
                ('imagenAuto', models.CharField(max_length=10)),
                ('nombreMecanico', models.CharField(max_length=45)),
                ('rutCliente', models.CharField(max_length=45)),
                ('costo', models.CharField(max_length=40)),
                ('garantia', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallerRayo.formulariocontacto')),
            ],
        ),
    ]
