# Generated by Django 4.0.5 on 2023-06-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerRayo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='trabajo',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='nombreCliente',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
