# Generated by Django 4.0.5 on 2023-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallerRayo', '0002_alter_atencion_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocontacto',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='marca',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='modeloAuto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='tipoServicio',
            field=models.CharField(default='', max_length=25),
        ),
    ]
